name: Deploy Phaser Application

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - name: Make .env
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
